version: '3.8'

services:
  web:
    image: gradle:6.4.1-jdk14
    volumes:
      - .:/app
      - /app/.gradle/
      - /app/build/
      - gradle:/root/.gradle
    working_dir: /app
    ports:
      - 5566:5566
    entrypoint:
      - "./gradlew"
      - "run"

  mysql:
    volumes:
      - ./mysql-compat.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  gradle: